"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navbar";
import { store } from "@/lib/redux/store";
import { Provider } from "react-redux";


const latoFont = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"]
});



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${latoFont.variable}  `}
      >
        <Provider store={store}>
        <NavBar/>
          <div className="container mx-auto">
            {children}          
          </div>
        </Provider>
      </body>
    </html>
  );
}
